# configs/models/CryptoMamba/v2.yaml
target: pl_modules.cmamba_module.CryptoMambaModule
params:
    num_features: 13
    hidden_dims: [13, 16, 32, 1]
    d_states: 128
    layer_density: 6
    revin: True
normalize: False
