# configs/models/CryptoMamba/v2.yaml
target: pl_modules.cmamba_module.CryptoMambaModule
params:
    num_features: 7
    hidden_dims: [6, 16, 32, 1]
    d_states: 64
    layer_density: 4
    loss: 'rmse'
    revin: True
normalize: False
