data_config: 'mode_1'
model: 'CMamba_v2'

name: 'CMamba'
max_epochs: 1000
use_volume: True
additional_features: []

hyperparams:
    optimizer: 'adam'
    lr: 0.0001
    # lr_step_size: 100 #StepLR
    # lr_gamma: 0.5 #StepLR
    weight_decay: 0.001
