additional_features:
- volatility_bbl
data_config: mode_1
hyperparams:
  alpha: 0.7
  loss_type: rmse
  lr: 0.0001
  optimizer: adamw
  weight_decay: 0.001
max_epochs: 1000
model: CMamba_v2
name: CMamba
skip_revin: []
use_volume: false
