data_config: 'mode_1'
model: 'CMamba_v2'

name: 'CMamba'
max_epochs: 1000
use_volume: False
additional_features: ["vol_current", "ITS_9", "trend_ichimoku_conv", "BB_Upper", "volatility_ui", "PSAR", "marketCap", "MEDPRICE", "TYPPRICE", "VWAP", "DX_14", "BB_Upper_5", "AVGPRICE", "ADDF_pct", "ADDF_diff", "TRANGE", "High_to_Low_Ratio"]

hyperparams:
    optimizer: 'adam'
    lr: 0.0001
    weight_decay: 0.001
    loss_type: 'hybrid'  # 新增：'hybrid' 启用 BCE + RMSE，'rmse' 用原
    alpha: 0.7  # 新增：RMSE 权重
