data_config: 'mode_1'
model: 'CMamba_v2'

name: 'CMamba'
max_epochs: 1000
use_volume: False
additional_features: ["log_return", "momentum_stoch"]

skip_revin: []

hyperparams:
    optimizer: 'adamw'
    lr: 0.0001
    weight_decay: 0.001
    loss_type: 'rmse'
    alpha: 0.7
    y_key: 'log_return'
