data_config: 'mode_1'
model: 'CMamba_v2'

name: 'CMamba'
max_epochs: 1000
use_volume: False
additional_features: ["vol_current","bitbo_sharpe_ratio","day_of_year","is_weekend"]

hyperparams:
    optimizer: 'adam'
    lr: 0.0001
    weight_decay: 0.001
    loss_type: 'hybrid'  # 新增：'hybrid' 启用 BCE + RMSE，'rmse' 用原
    alpha: 0.7  # 新增：RMSE 权重
