data_config: 'mode_1'
model: 'CMamba_v2'

name: 'CMamba'
max_epochs: 1000
use_volume: False
additional_features: ["Open", "High", "Low", "Close", "log_return_high"]

skip_revin: []

# 对应 Low 模型的 [0.05, 0.20, 0.40, 0.60]
# 解释：
# 0.95: 只有 5% 概率涨破 (极限阻力位，空单止损)
# 0.80: 只有 20% 概率涨破 (对应 Low 的 0.20，深坑变高塔，适合空单 DCA 最后一枪)
# 0.60: 只有 40% 概率涨破
# 0.40: 只有 60% 概率涨破 (比较容易达到的高点，空单第一枪)
hyperparams:
    optimizer: 'adamw'
    lr: 0.0001
    weight_decay: 0.001
    alpha: 0.7
    y_key: 'log_return_high'
    loss_type: 'quantile'
    quantiles: [0.95, 0.80, 0.60, 0.40]
    output_dim: 4
