data_config: 'mode_1'
model: 'CMamba_v2'

name: 'CMamba'
max_epochs: 1000
use_volume: True
additional_features: ["MACD_Hist","MACD_Signal"]

hyperparams:
    optimizer: 'adam'
    lr: 0.0001
    weight_decay: 0.001
