# n416-long
# Model: eth_long_260212
start_date: '2018-03-01'
end_date: '2025-09-30'
root: ./data
checkpoints: ./checkpoints
date_format: '%Y-%m-%d'
data_path: ./data/ETH-USD.csv
train_interval: ['2018-03-01', '2024-06-01']
val_interval: ['2024-06-01', '2025-03-01']
test_interval: ['2025-03-01', '2025-09-30']
additional_features: []
fixed_features:
- fng_value
- fng_lag_2
- PF_Open_Gap
- HT_SINE_leadsine
- daily_range_pct
- DX_14
- CHOP_14
- Close_to_High_Ratio
- PF_K_Body


