# n88B-short
# Model: eth_short_260212
start_date: '2018-03-01'
end_date: '2025-09-30'
root: ./data
checkpoints: ./checkpoints
date_format: '%Y-%m-%d'
data_path: ./data/ETH-USD.csv
train_interval: ['2018-03-01', '2024-06-01']
val_interval: ['2024-06-01', '2025-03-01']
test_interval: ['2025-03-01', '2025-09-30']
additional_features: []
fixed_features:
- trend_dpo
- daily_range_pct
- momentum_ao
- FastK_5
- momentum_wr
- fng_lag_3
- divergence_rank_diff
- momentum_pvo_signal
- PF_K_Body
- CMF
- bar_strength
- Close_to_Open_Ratio


