start_date: "2018-03-01"
end_date: "2025-09-30"
root: "./data"
checkpoints: "./checkpoints"
date_format: "%Y-%m-%d"
data_path: "./data/BTC-USD.csv"
train_interval: ["2018-03-01", "2024-06-01"]
val_interval: ["2024-06-01", "2025-03-01"]
test_interval: ["2025-03-01", "2025-09-30"]
additional_features: []
fixed_features:
- HT_DCPERIOD
- ADXR_14
- MACDEXT
- fng_lag_3
- trend_dpo
- CMF
- CHOP_14
- momentum_pvo_signal
- bar_strength
- next_day_of_month
- fng_range_interaction
- Close_to_Low_Ratio
- momentum_wr

