start_date: "2018-03-01"
end_date: "2025-09-30"
root: "./data"
checkpoints: "./checkpoints"
date_format: "%Y-%m-%d"
data_path: "./data/ETH-USD.csv"
train_interval: ["2018-03-01", "2024-06-01"]
val_interval: ["2024-06-01", "2025-03-01"]
test_interval: ["2025-03-01", "2025-09-30"]
additional_features: []
fixed_features:
- BOP
- PF_K_UpShadow
- Bitbo_Sharpe
- vol_current
- vol_fear_interaction
- AROON_osc_14
- divergence_rank_diff
- Close_to_Low_Ratio
- Vol_ROC
- ADXR_14
- next_day_of_month
- momentum_ppo_hist
- HT_SINE_leadsine
- PF_K_Body
- momentum_pvo_hist
- next_halving_pos_angle
- trend_stc
- MACD_Signal
- next_weekday
- MACDFIX_Hist
- FastD_RSI_14
- ADI
- fng_norm
- Close_to_Open_Ratio
- emd_energy_imf2
- CCI_14
- daily_range_pct
- trend_kst
- TRIX_30
- SlowK_5
- PF_Open_Gap
- CHOP_14
- fng_lag_2
- trend_mass_index
- volume_obv
- DX_14
- volume_nvi
- FastK_5
- pattern_sentiment_score
- Close_to_High_Ratio
- HT_DCPERIOD
