start_date: "2018-03-01"
end_date: "2025-09-30"
root: "./data"
checkpoints: "./checkpoints"
date_format: "%Y-%m-%d"
data_path: "./data/ETH-USD.csv"
train_interval: ["2018-03-01", "2024-06-01"]
val_interval: ["2024-06-01", "2025-03-01"]
test_interval: ["2025-03-01", "2025-09-30"]
fixed_features: ["PF_Close_Chg", "PF_Open_Gap", "PF_High_Dev", "PF_Low_Dev"]
additional_features: [
    "ISB_26",
    "ISA_9",
    "Stoch_D",
    "ATR_14",
    "CMF",
    "PSAR",
    "OBV",
    "ADXR_14",
    "AROON_osc_14",
    "BOP",
    "CCI_14",
    "CMO_14",
    "DX_14",
    "MACDEXT",
    "MACDEXT_Signal",
    "MACDEXT_Hist",
    "MACDFIX",
    "MACDFIX_Signal",
    "MACDFIX_Hist",
    "MINUS_DM_14",
    "MOM_10",
    "PLUS_DM_14",
    "PPO",
    "ROC_10",
    "ROCP_10",
    "ROCR_10",
    "ROCR100_10",
    "SlowK_5",
    "SlowD_5",
    "FastK_5",
    "FastD_5",
    "FastK_RSI_14",
    "FastD_RSI_14",
    "TRIX_30",
    "BB_Upper_5",
    "BB_Middle_5",
    "BB_Lower_5",
    "DEMA_30",
    "EMA_21",
    "EMA_100",
    "HT_TRENDLINE",
    "KAMA_30",
    "MA_21",
    "MA_100",
    "MAMA",
    "FAMA",
    "MIDPOINT_14",
    "MIDPRICE_14",
    "SAREXT",
    "SMA_21",
    "SMA_100",
    "T3_5",
    "TEMA_30",
    "TRIMA_30",
    "WMA_30",
    "NATR_14",
    "TRANGE",
    "AD",
    "High_Low_Spread",
    "Open_Close_Spread",
    "Log_Volume",
    "Log_Return",
    "vol_current",
    "vol_shock",
    "HT_DCPERIOD",
    "HT_DCPHASE",
    "HT_PHASOR_inphase",
    "HT_PHASOR_quadrature",
    "HT_SINE_sine",
    "HT_SINE_leadsine",
    "HT_TRENDMODE",
    "CDLDOJI",
    "Close_to_Open_Ratio",
    "High_to_Low_Ratio",
    "Close_to_High_Ratio",
    "Close_to_Low_Ratio",
    "Open_to_High_Ratio",
    "Open_to_Low_Ratio",
    "MAVP",
    "ICS_26",
    "VWAP",
    "SuperTrend",
    "CHOP_14",
    "volume_adi",
    "volume_obv",
    "volume_cmf",
    "volume_fi",
    "volume_em",
    "volume_sma_em",
    "volume_vpt",
    "volume_vwap",
    "volume_mfi",
    "volume_nvi",
    "volatility_bbm",
    "volatility_bbh",
    "volatility_bbl",
    "volatility_bbw",
    "volatility_bbp",
    "volatility_bbhi",
    "volatility_bbli",
    "volatility_kcc",
    "volatility_kch",
    "volatility_kcl",
    "volatility_kcw",
    "volatility_kcp",
    "volatility_kchi",
    "volatility_kcli",
    "volatility_dcl",
    "volatility_dch",
    "volatility_dcm",
    "volatility_dcw",
    "volatility_dcp",
    "volatility_atr",
    "volatility_ui",
    "trend_macd",
    "trend_macd_signal",
    "trend_macd_diff",
    "trend_sma_fast",
    "trend_sma_slow",
    "trend_ema_fast",
    "trend_ema_slow",
    "trend_vortex_ind_pos",
    "trend_vortex_ind_neg",
    "trend_vortex_ind_diff",
    "trend_trix",
    "trend_mass_index",
    "trend_dpo",
    "trend_kst",
    "trend_kst_sig",
    "trend_kst_diff",
    "trend_ichimoku_conv",
    "trend_ichimoku_base",
    "trend_ichimoku_a",
    "trend_ichimoku_b",
    "trend_stc",
    "trend_adx",
    "trend_adx_pos",
    "trend_adx_neg",
    "trend_cci",
    "trend_visual_ichimoku_a",
    "trend_visual_ichimoku_b",
    "trend_aroon_up",
    "trend_aroon_down",
    "trend_aroon_ind",
    "trend_psar_up",
    "trend_psar_down",
    "trend_psar_up_indicator",
    "trend_psar_down_indicator",
    "momentum_rsi",
    "momentum_stoch_rsi",
    "momentum_stoch_rsi_k",
    "momentum_stoch_rsi_d",
    "momentum_tsi",
    "momentum_uo",
    "momentum_stoch",
    "momentum_stoch_signal",
    "momentum_wr",
    "momentum_ao",
    "momentum_roc",
    "momentum_ppo",
    "momentum_ppo_signal",
    "momentum_ppo_hist",
    "momentum_pvo",
    "momentum_pvo_signal",
    "momentum_pvo_hist",
    "momentum_kama",
    "others_dr",
    "others_dlr",
    "others_cr",
    "EWMA_14",
    "bar_strength",
    "gk_vol",
    "Vol_Ratio",
    "Vol_Z",
    "Signed_Vol_Norm",
    "Force_Index",
    "Vol_ROC",
    "MFI",
    "EOM",
    "rvol",
    "Dist_VWAP",
    "weekday",
    "month",
    "day_of_year",
    "day_of_month",
    "is_weekend",
    "days_in_month",
    "next_weekday",
    "next_month",
    "next_day_of_year",
    "next_day_of_month",
    "next_days_in_month",
    "next_is_weekend",
    "next_is_month_start",
    "next_is_month_end",
    "next_is_quarter_end",
    "weekend_phase",
    "days_since_last_halving",
    "days_before_next_halving",
    "next_days_since_last",
    "next_days_before_next",
    "halving_countdown_30",
    "wd_angle",
    "yr_angle",
    "mn_angle",
    "daymn_angle",
    "next_daymn_angle",
    "next_wd_angle",
    "next_yr_angle",
    "next_mn_angle",
    "halving_pos_angle",
    "next_halving_pos_angle",
    "month_3_angle",
    "next_month_3_angle",
    "month_6_angle",
    "next_month_6_angle",
    "next_yr_angle_norm",
    "yr_angle_norm",
    "Return",
    "Bitbo_Sharpe",
    "fng_value",
    "fng_norm",
    "fng_lag_1",
    "fng_lag_2",
    "fng_lag_3",
    "fng_diff",
    "fng_accel",
    "fng_volatility_7d",
    "is_extreme_fear",
    "is_extreme_greed",
    "divergence_flag",
    "divergence_rank_diff",
    "vol_fear_interaction",
    "daily_range_pct",
    "fng_range_interaction",
    "fourier_amp_1",
    "fourier_amp_2",
    "fourier_amp_3",
    "wavelet_energy_approx",
    "wavelet_energy_detail1",
    "wavelet_energy_detail2",
    "emd_energy_imf1",
    "emd_energy_imf2",
    "vmd_energy_mode1",
    "vmd_energy_mode2",
    "ewt_energy_mode1",
    "ewt_energy_mode2",
    "shocklet_energy_mode",
    "hurst_exponent",
    "CDL2CROWS",
    "CDL3BLACKCROWS",
    "CDL3INSIDE",
    "CDL3LINESTRIKE",
    "CDL3OUTSIDE",
    "CDL3STARSINSOUTH",
    "CDL3WHITESOLDIERS",
    "CDLABANDONEDBABY",
    "CDLADVANCEBLOCK",
    "CDLBELTHOLD",
    "CDLBREAKAWAY",
    "CDLCLOSINGMARUBOZU",
    "CDLCONCEALBABYSWALL",
    "CDLCOUNTERATTACK",
    "CDLDARKCLOUDCOVER",
    "CDLDOJISTAR",
    "CDLDRAGONFLYDOJI",
    "CDLENGULFING",
    "CDLEVENINGDOJISTAR",
    "CDLEVENINGSTAR",
    "CDLGAPSIDESIDEWHITE",
    "CDLGRAVESTONEDOJI",
    "CDLHAMMER",
    "CDLHANGINGMAN",
    "CDLHARAMI",
    "CDLHARAMICROSS",
    "CDLHIGHWAVE",
    "CDLHIKKAKE",
    "CDLHIKKAKEMOD",
    "CDLHOMINGPIGEON",
    "CDLIDENTICAL3CROWS",
    "CDLINNECK",
    "CDLINVERTEDHAMMER",
    "CDLKICKING",
    "CDLKICKINGBYLENGTH",
    "CDLLADDERBOTTOM",
    "CDLLONGLEGGEDDOJI",
    "CDLLONGLINE",
    "CDLMARUBOZU",
    "CDLMATCHINGLOW",
    "CDLMATHOLD",
    "CDLMORNINGDOJISTAR",
    "CDLMORNINGSTAR",
    "CDLONNECK",
    "CDLPIERCING",
    "CDLRICKSHAWMAN",
    "CDLRISEFALL3METHODS",
    "CDLSEPARATINGLINES",
    "CDLSHOOTINGSTAR",
    "CDLSHORTLINE",
    "CDLSPINNINGTOP",
    "CDLSTALLEDPATTERN",
    "CDLSTICKSANDWICH",
    "CDLTAKURI",
    "CDLTASUKIGAP",
    "CDLTHRUSTING",
    "CDLTRISTAR",
    "CDLUNIQUE3RIVER",
    "CDLUPSIDEGAP2CROWS",
    "CDLXSIDEGAP3METHODS",
    "bullish_pattern_count",
    "bearish_pattern_count",
    "pattern_sentiment_score",
    "PF_K_Body",
    "PF_K_UpShadow",
    "PF_K_LowShadow",
    "PF_K_Range",
    "PF_MCap_Chg"
]
