start_date: "2018-03-01"
end_date: "2025-09-30"
root: "./data"
checkpoints: "./checkpoints"
date_format: "%Y-%m-%d"
data_path: "./data/ETH-USD.csv"
train_interval: ["2018-03-01", "2024-06-01"]
val_interval: ["2024-06-01", "2025-03-01"]
test_interval: ["2025-03-01", "2025-09-30"]
additional_features: []
fixed_features:
- fng_lag_2
- HT_SINE_leadsine
- next_weekday
- daily_range_pct
- ADI
- vol_current
- trend_mass_index
- AROON_osc_14
- PF_K_Body
- CHOP_14
- PF_K_UpShadow
- MACDFIX_Hist
- ADXR_14
- TRIX_30
- DX_14
- Close_to_High_Ratio
